version: '3'
services:
 web:
   restart: always
   build: 
    context: .
    args:
     RUBY_VER: ${RUBY_VER}
   ports:
     - "80:80"
   volumes:
     - /var/www/html:/var/www/html
     - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
   environment:
      APP_DB_DATABASE: ${POSTGRES_DB}
      APP_DB_USERNAME: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_DB_HOST: postgres
   depends_on:
    - postgres
 postgres:
    image: postgres:10.6
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
     - ./tmp/db:/var/lib/postgresql/data


